theme: charlolamode
title: david.kun
baseURL: https://davidkun.github.io

menu:
    main:
        - name: posts
          url: /posts/
          weight: 1
        - name: tags
          url: /tags/
          weight: 2
        - name: about
          url: /about/
          weight: 3

params:
    author: David Kun
    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: hello
        description: |
          i'm a software dev with

          an aerospace engineering background
        imageUrl: "/images/profile.png"
        imageTitle: my image
        imageWidth: 218
        imageHeight: 277
        buttons:
            # - name: name
              # url: link
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/davidkun"
        - name: linkedin
          url: "https://www.linkedin.com/in/davidwkun"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true